### PR TITLE
Add : Enemy types

### PR DESCRIPTION
**Pull request by xxfast**
added all the enemy types as discussed; the values might need to be tweaked, but the behavior is implemented

### CODE REVIEW

**Comment by xxfast** [comment]
[Enemy Type - Tank](https://trello.com/c/2mPqfkZo/4-enemy-type-tank)

**Comment by xxfast** [comment]
[Enemy Type - Agressive](https://trello.com/c/p8VCWWnA/5-enemy-type-agressive)

**Comment by xxfast** [comment]
[Enemy Type - Boss](https://trello.com/c/RKYCBjCK/6-enemy-type-boss)

**Review by JPGalovic — APPROVED** [review]
Love it, Enemy types work well, I like that their hp is displayed by their size.
1 small issue but will put in as bug, larger enemies can still hit player evan if player is moving, may be an issue with mechanics, will add as bug to be solved.

**Pull request merged**
