### PR TITLE
Add: Collapsable enemy

### PR DESCRIPTION
**Pull request by xxfast**
all the enemies glue together on collision with each other

### CODE REVIEW

**Comment by xxfast** [comment]
[Enemy Mechanic - Collapsable Behavior](https://trello.com/c/10MMAjaJ/1-enemy-mechanic-collapsable-behavior)

**Review by Xavier-Gibbon — CHANGES_REQUESTED** [review]
A cluster of enemies will sometimes be entirely killed when only one part of it is attacked by the player. Not sure what causes this

**Comment by xxfast** [comment]
Updated the behaviour with a group controller. Now only aggressive show this behaviour and they only group up on collision with each other. 
zi8wncch8gkga

**Review by JPGalovic — APPROVED** [review]
Works as intended (determined by discussion on slack)
Needs AI to be implemented to differntiate from what was precived to be inital intent.

**Pull request merged**
