### PR TITLE
Add: Minimum Stamina

### PR DESCRIPTION
**Pull request by JPGalovic**
Minimum Stamina defines minimum stamina to begin moving
Added Moving Flagg, as player can continue moving until crash, just need
minimum to start moving.

### CODE REVIEW

**Comment by JPGalovic** [comment]
[Player Mechanic - Minimum stamina to move](https://trello.com/c/hfegPm0x/11-player-mechanic-minimum-stamina-to-move)

**Review by Xavier-Gibbon — CHANGES_REQUESTED** [review]
Attempting to move the player before they have enough stamina to move will still drain the players stamina

**Comment by JPGalovic** [comment]
@Xavier-Gibbon what code is causing that?

**Review by Xavier-Gibbon — APPROVED** [review]
Changes work, everything looks good. Good to merge.

**Pull request merged**
